---
# Security Hardening Playbook
# Demonstrates: security best practices, conditionals, handlers
#
# Usage:
#   ansible-playbook -i dev/hosts security-hardening.yml
#   ansible-playbook -i prod/hosts security-hardening.yml --check

- name: Apply security hardening
  hosts: all
  gather_facts: yes
  become: yes
  
  vars:
    # Additional security packages
    extra_security_packages:
      - aide
      - rkhunter
      - lynis
  
  pre_tasks:
    - name: Display security hardening notice
      ansible.builtin.debug:
        msg: |
          Starting security hardening for {{ hostname }}
          Environment: {{ environment }}
          This will apply security best practices
  
  tasks:
    - name: Install additional security tools
      ansible.builtin.package:
        name: "{{ extra_security_packages }}"
        state: present
      when: environment == "production"
      tags: ['security', 'packages']
    
    - name: Configure kernel parameters for security
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      loop:
        - { name: 'net.ipv4.conf.all.accept_source_route', value: '0' }
        - { name: 'net.ipv4.conf.default.accept_source_route', value: '0' }
        - { name: 'net.ipv4.conf.all.accept_redirects', value: '0' }
        - { name: 'net.ipv4.conf.default.accept_redirects', value: '0' }
        - { name: 'net.ipv4.icmp_echo_ignore_broadcasts', value: '1' }
        - { name: 'net.ipv4.conf.all.log_martians', value: '1' }
      tags: ['security', 'kernel']
    
    - name: Set strict file permissions on sensitive files
      ansible.builtin.file:
        path: "{{ item.path }}"
        mode: "{{ item.mode }}"
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group | default('root') }}"
      loop:
        - { path: '/etc/ssh/sshd_config', mode: '0600' }
        - { path: '/etc/shadow', mode: '0000' }
        - { path: '/etc/gshadow', mode: '0000' }
      tags: ['security', 'permissions']
    
    - name: Disable unnecessary services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - bluetooth
        - cups
      failed_when: false
      tags: ['security', 'services']
    
    - name: Configure password policy
      ansible.builtin.lineinfile:
        path: /etc/login.defs
        regexp: "^{{ item.key }}"
        line: "{{ item.key }} {{ item.value }}"
        state: present
      loop:
        - { key: 'PASS_MAX_DAYS', value: '90' }
        - { key: 'PASS_MIN_DAYS', value: '7' }
        - { key: 'PASS_MIN_LEN', value: '12' }
        - { key: 'PASS_WARN_AGE', value: '14' }
      when: environment == "production"
      tags: ['security', 'password']
    
    - name: Configure auditd rules (production only)
      ansible.builtin.copy:
        content: |
          # Audit rules for {{ hostname }}
          -w /etc/passwd -p wa -k passwd_changes
          -w /etc/group -p wa -k group_changes
          -w /etc/shadow -p wa -k shadow_changes
          -w /etc/sudoers -p wa -k sudoers_changes
          -w /var/log/auth.log -p wa -k auth_log_changes
          -a always,exit -F arch=b64 -S adjtimex -S settimeofday -k time_change
          -w /etc/ssh/sshd_config -p wa -k sshd_config_changes
        dest: /etc/audit/rules.d/custom.rules
        mode: '0640'
      when:
        - environment == "production"
        - audit_enabled | default(false)
      notify: restart auditd
      tags: ['security', 'audit']
    
    - name: Create security scan script
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          # Security scan script for {{ hostname }}
          # Environment: {{ environment }}
          
          echo "=== Security Scan Report ==="
          echo "Date: $(date)"
          echo "Hostname: $(hostname)"
          echo ""
          
          echo "Failed login attempts (last 100):"
          grep "Failed password" /var/log/auth.log | tail -20 || echo "None"
          echo ""
          
          echo "Active network connections:"
          ss -tuln
          echo ""
          
          echo "Running processes by user:"
          ps aux | awk '{print $1}' | sort | uniq -c | sort -rn | head -10
          echo ""
          
          echo "Firewall status:"
          ufw status verbose || echo "UFW not configured"
        dest: /opt/scripts/security-scan.sh
        mode: '0750'
      tags: ['security', 'monitoring']
    
    - name: Setup daily security scan cron (production)
      ansible.builtin.cron:
        name: "Daily security scan"
        minute: "0"
        hour: "1"
        job: "/opt/scripts/security-scan.sh > /var/log/security-scan.log 2>&1"
        user: root
        state: present
      when: environment == "production"
      tags: ['security', 'monitoring']
  
  post_tasks:
    - name: Security hardening summary
      ansible.builtin.debug:
        msg: |
          Security hardening completed for {{ hostname }}
          Environment: {{ environment }}
          - Kernel parameters: configured
          - File permissions: set
          - Security tools: {{ 'installed' if environment == 'production' else 'skipped (dev)' }}
          - Audit rules: {{ 'configured' if environment == 'production' else 'skipped (dev)' }}

  handlers:
    - name: restart auditd
      ansible.builtin.service:
        name: auditd
        state: restarted
